name: Original PR from Lokalise

on: workflow_dispatch

jobs:
  lokalise:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Lokalise Download
        run: |
          curl --request POST \
          --url https://api.lokalise.com/api2/projects/388922246710958f0774f6.27264383/files/download \
          --header 'X-Api-Token: ${{ secrets.LOKALISE_KEY }}' \
          --header 'accept: application/json' \
          --header 'content-type: application/json' \
          --data '
          {
          "triggers": [
            "github"
          ],
          "format": "yaml",
          "original_filenames": true,
          "directory_prefix": "/",
          "all_platforms": true,
          "export_sort": "a_z",
          "export_empty_as": "empty",
          "include_comments": false,
          "include_description": false,
          "replace_breaks": false,
          "disable_references": false,
          "plural_format": "icu",
          "placeholder_format": "icu",
          "icu_numeric": true,
          "indentation": "2sp",
          "yaml_include_root": false
          }'