name: Auto-merge MyLokalise PRs

on:
  pull_request:
    types: [opened]
    branches:
      - 'master' #my branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  #checks: read  ??do I need this?

jobs:
  auto-merge-lokalise:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'MyPR-Title') 
    steps:
      - name: Check if PR title contains - MyPR-Title
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "This PR appears to be from Lokalise and will be auto-merged"

      - name: Wait for format-yml-translations workflow to complete
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          running-workflow-name: 'Format YAML Translations'
          check-name: 'sort-yaml'

      - name: Wait for all other checks to complete
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          running-workflow-name: 'auto-merge-lokalise'

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: |
            ${{ github.event.pull_request.body }}
            
            Automatically merged MyLokalise translation update.
