name: Auto-merge MyLokalise PRs

on:
  pull_request:
    types: [opened]
    branches:
      - 'master' #my branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  #checks: read  ??do I need this?

jobs:
  auto-merge-lokalise:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.title, 'Lokalise: Translations update')"
    steps:
      - name: Check if PR title contains - MyPR-Title
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "This PR appears to be from Lokalise and will be auto-merged"

      - name: Add Lokalise label to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['lokalise', 'automerge']
            })

      - name: Wait for format-yml-translations workflow to complete
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          running-workflow-name: 'Format YAML Translations'
          check-name: 'sort-yaml'

      - name: Wait for all other checks to complete
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          running-workflow-name: 'auto-merge-lokalise'

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG: "TRACE"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_METHOD_LABEL_REQUIRED: "false"
          MERGE_COMMIT_MESSAGE: |
            ${{ github.event.pull_request.body }}
            
            Automatically merged MyLokalise translation update.
