name: Run every 10 minutes

on:
  schedule:
    - cron: '*/10 22-23,0-7 * * 1-5'  # Runs every 10 minutes, 8:00am to 5:00pm Monday to Friday
    #UTC weekday version (not good) - cron: '*/10 22-23,0-7 * * 0-4'  # Runs every 10 minutes

jobs:
  run_every_10_minutes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello! This workflow runs every 10 minutes in AU working hours. Let's go."
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install lokalise library
        run: npm install @lokalise/node-api

      - name: Run test Node script
        run: node public/lokalise-test-script.js