name: PR from Lokalise using lokalise-pull-action

on: workflow_dispatch

jobs:
  lokalise:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v3.8.0
        with:
          api_token: ${{ secrets.LOKALISE_KEY }}
          project_id: "66835468677f4447c39f72.08805740"
          file_format: yaml
          translations_path: |
            "translations"
          additional_params: |
            --indentation=2sp
            --export-empty-as=empty
            --export-sort=a_z
            --replace-breaks=false
            --yaml-include-root=false
            --original-filenames=true
            --directory-prefix="/"
            --all-platforms=true
            --include-comments=false
            --include-description=false
            --disable-references=false
            --plural-format=icu
            --placeholder-format=icu
            --icu-numeric=true
